### PR TITLE
Adding support for Scala 2.12

### PR DESCRIPTION
**Pull request by csaltos**
Thank you for your library, I hope this helps.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by csaltos** [comment]
I signed it!

Snowplow CLA bot wrote:

**Comment by snowplowcla** [comment]
Confirmed! @csaltos has signed the Individual Contributor License Agreement. Thanks so much

**Comment by andrusha** [comment]
Any chance of this being merged? 2.12 is mainstream now

**Comment by BenFradet** [comment]
closing as superseded by #38, thanks anyway :+1:

**Pull request closed without merging**
