### PR TITLE
 Switch from scalaz to cats (closes #61)

### LINKED ISSUE #61: Switch from scalaz to cats

### PR DESCRIPTION
**Pull request by yeonhoo**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by yeonhoo** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @yeonhoo has signed the Individual Contributor License Agreement. Thanks so much

**Comment by BenFradet** [comment]
can you remove the formatting stuff? it makes it difficult to review

**Comment by BenFradet** [comment]
actually you can now just rebase with develop since I just merged the scalafmt :+1:

**Comment by yeonhoo** [comment]
I made another PR, (I'm not sure if it is the right workflow) and I've removed the formatting stuff. 
Should I remove more?

**Comment by BenFradet** [comment]
We usually keep the same pr open and update it wrt the base branch through rebasing: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Pull request closed without merging**
