### PR TITLE
Add ASN in the result

### PR DESCRIPTION
**Pull request by BagusThanatos**
- [x] Have you signed the [contributor license agreement](https://github.com/snowplow/snowplow/wiki/CLA)?
- [x] Have you read the [contributing guide](https://github.com/snowplow/scala-maxmind-iplookups/blob/develop/CONTRIBUTING.md)?
- [x] Have you added the appropriate unit tests?
- [x] Have you run the tests through `sbt test`?
- [x] Is your pull request against the `develop` branch?

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by BagusThanatos** [comment]
I signed it!

**Comment by paulboocock** [comment]
I can confirm the CLA has been signed.

**Comment by BagusThanatos** [comment]
Thanks for confirming @paulboocock !
Any feedback on this PR or anything I can do to get this processed?

**Comment by paulboocock** [comment]
This isn't really a PR that I can lend a hand to. I will raise it internally though and see if we have any plans for this library or if we can schedule a release.

**Comment by BagusThanatos** [comment]
Closing this as there's no update on this.

Thanks!

**Pull request closed without merging**
